repo: https://git.openwrt.org/openwrt/openwrt.git
branch: master
upload_release: true

scripts_dir: scripts
feeds_dir: feeds
config_dir: config

configs:
  - name: naopi_r2s_base
    config: naopi-r2s-base
    feeds: 
      - base.conf
  - name: naopi_r2s_std
    config: naopi-r2s-std
    feeds: 
      - base.conf
    scripts:
      - add-openclash.sh
      - add-unblockneteasemusic.sh
